### PR TITLE
Interactive No. Guessing Game in Python

### PR DESCRIPTION
**Pull request by avigarg820**
# Description

This is a small project in the form of a game that I made in Python, Anyone looking to engage in an interactive game of guessing, and give themselves a boost should attend.  Demo File is linked in the README file @anjali1102
[README.md](https://github.com/avigarg820/Hacktober2022/files/9742426/README.md)
Original Project Repo Link: https://github.com/avigarg820/Interactive-No.-Guessing-Game-.py.

Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ]New feature (non-breaking change which adds functionality)

# Checklist:

- [✓ ] My code follows the style guidelines(Clean Code) of this project
- [✓ ] I have performed a self-review of my own code
- [ ✓ ] I have commented my code, particularly in hard-to-understand areas
- [ ✓ ] I have created a helpful and easy to understand `README.md`
- [ ✓ ] I have made corresponding changes to the documentation
- [ ✓ ] My changes generate no new warnings
- [ ✓ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by avigarg820** [comment]
HI @anjali1102 ,I developed this project and included a README file including a full list of the project's requirements. For confirmation, I've also included the URL to the original repo. Please take this into consideration for the Hacktoberfest-Accepted tag. Thank you so much. Have a great day

**Comment by avigarg820** [comment]
@anjali1102  Well ma'am, this will be my first PR. Please let me know if this is off-topic for hacktoberfest. Should I continue adding projects while I wait for the hacktoberfest tag? Please let me know; either response is OK.

**Comment by anjali1102** [comment]
@avigarg820 ok

**Comment by anjali1102** [comment]
@avigarg820 it's merged , so i am unable to add tag now, 
give another project or this project again as a new PR

**Comment by anjali1102** [comment]
give a new PR of any project, will merge it with tags

**Comment by avigarg820** [comment]
ok lemme try again mam

**Pull request merged**
